language: python

python:
  - 2.7
  - 3.5
  - 3.6

env:
  - DJANGOVER=django110
  - DJANGOVER=django111

install:
  - pip install tox

matrix:
  exclude:
  - python: 2.7
    env: DJANGOVER=django20

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGOVER}
  - tox -r -e "$TOX_ENV"
